# Generated by Django 6.0.3 on 2026-03-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_id', models.CharField(max_length=50)),
                ('crop_name', models.CharField(max_length=100)),
                ('symptoms', models.TextField()),
                ('top_disease', models.CharField(blank=True, max_length=200)),
                ('confidence', models.CharField(blank=True, max_length=20)),
                ('results_json', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Query History',
                'verbose_name_plural': 'Query Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
